//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BeestjeOpJeFeestje.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Beast = new HashSet<Beast>();
        }
    
        [Key]
        public int ID { get; set; }
        [Key]
        public int ContactpersonID { get; set; }

        [DataType(DataType.Date)]
        [Required]
        [DisplayName("Datum")]
        public System.DateTime Date { get; set; }
    
        public virtual ContactPerson ContactPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beast> Beast { get; set; }
    }
}
