//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeestjeOpJeFeestje.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking 
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Beast = new HashSet<Beast>();
            this.Accessory = new HashSet<Accessory>();
            Discounts = new List<Discount>();
        }

        [Key]
        public int ID { get; set; }
        public int ContactpersonID { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayName("Datum booking")]
        public System.DateTime Date { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [DisplayName("Prijs boeking")]
        public decimal Price { get; set; }

        public ICollection<Discount> Discounts { get; set; }

        public virtual ContactPerson ContactPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beast> Beast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accessory> Accessory { get; set; }
    }
}
